[package]
name = "river_dreams"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
crossterm = "0.26.1"
local-ip-address = "0.5.1"
num-format = "0.4.4"
sysinfo = "0.28.4"
