[package]
name = "river-dreams"
version = "2.1.1"
edition = "2021"

[profile.release]
strip = true
lto = true
codegen-units = 1

[dependencies]
chrono = "0.4.26"
crossterm = "0.26.1"
local-ip-address = "0.5.4"
sysinfo = "0.29.7"
